version: "3"
services:
  node-cont:
    image: node-cont
    container_name: node-cont
    build: .
    ports:
      - "3000:4000"
    environment:
      - PORT=4000
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-cont
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
