version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
  node-cont:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start
